[package]
name = "combinators"
version = "0.1.0"
edition = "2021"
# channel = "nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.0"
ctrlc = "3.2.1"
